### ISSUE TITLE
使用系统的DownloadManager有机型适配问题吗？

### ISSUE THREAD

**Issue by candebbs** [simplepeng/Updater#1]
使用DownloadManager，很方便下载，但有些room去掉DownloadManager的，有测试过不？

**Comment by simplepeng** [comment]
目前自己在MIUI，Flyme，color OS，一加氧OS测试没有问题，自家产品就是用的这个，目前还没遇到bug，如果在使用过程产生了bug，请提交一个issue，我会尽快解决的。

**Comment by singlenobleJ** [comment]
红米四 6.0.1系统安装时闪退

**Comment by simplepeng** [comment]
@singlenobleJ 能贴一下崩溃日志吗？
